version: "3"

services:
  redis:
    image: "redis:alpine"
    container_name: sodar_redis
    ports:
      - "6633:6379"
    expose:
      - "6379"
    networks:
      - sodar_bridge

  irods_main:
    container_name: sodar_irods_main
    build:
      context: ./irods
      dockerfile: ./Dockerfile
    ports:
      - "4477:1247"
    expose:
      - "1247"
    environment:
      - IRODS_ZONE_NAME=omicsZone
    networks:
      - sodar_bridge

  irods_test:
    container_name: sodar_irods_test
    build:
      context: ./irods
      dockerfile: ./Dockerfile
    ports:
    - "4488:1247"
    expose:
    - "1247"
    environment:
    - IRODS_ZONE_NAME=omicsZone
    networks:
    - sodar_bridge

networks:
  sodar_bridge:
    driver: bridge
