version: "3"

services:
  redis:
    image: "redis:alpine"
    container_name: sodar_redis
    ports:
      - "6633:6379"
    expose:
      - "6379"
    networks:
      - sodar_bridge

  irods:
    container_name: sodar_irods
    build:
      context: ./irods
      dockerfile: ./Dockerfile
    ports:
      - "4477:1247"
    expose:
      - "1247"
    environment:
      - IRODS_ZONE_NAME=omicsZone
    networks:
      - sodar_bridge

networks:
  sodar_bridge:
    driver: bridge
