version: "3"

services:
  redis:
    image: "redis:alpine"
    container_name: omics_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - omics_bridge

  irods:
    container_name: omics_irods
    build:
      context: ./irods
      dockerfile: ./Dockerfile
    ports:
      - "1247:1247"
    expose:
      - "1247"
    environment:
      - IRODS_ZONE_NAME=omicsZone
    networks:
      - omics_bridge

  omics_taskflow:
    image: "gitlab.bihealth.org:4567/cubi_data_mgmt/omics_taskflow/omics_taskflow:latest"
    container_name: omics_taskflow_app
    ports:
      - "5005:5005"
    expose:
      - "5005"
    depends_on:
      - redis
      - irods
    environment:
      - APP=omics_taskflow_app
      - TASKFLOW_REDIS_HOST=omics_redis
      - TASKFLOW_OMICS_URL=http://172.17.0.1:8000
      - TASKFLOW_IRODS_HOST=omics_irods
      - TASKFLOW_ALLOW_IRODS_CLEANUP=1
    networks:
      - omics_bridge

  omics_irods_rest:
    image: "gitlab.bihealth.org:4567/cubi_data_mgmt/omics_irods_rest/omics_irods_rest:latest"
    container_name: omics_irods_rest_app
    ports:
      - "5006:5006"
    expose:
      - "5006"
    depends_on:
      - irods
    environment:
      - APP=omics_irods_rest_app
      - IRODS_HOST=omics_irods
    networks:
      - omics_bridge

  madeline:
    image: "gitlab.bihealth.org:4567/cubi_data_mgmt/madeline_docker:latest"
    container_name: madeline
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      - IRODS_HOST=omics_irods
    networks:
      - omics_bridge

  cloud_browser:
    container_name: omics_cloud_browser
    build:
      context: ./cloud_browser
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    expose:
      - "8080"
    depends_on:
      - irods
    networks:
      - omics_bridge

networks:
  omics_bridge:
    driver: bridge
